import { APP_NAME } from '../../constants';

const GET_ALL_SUITES = `${APP_NAME}/GET_ALL_SUITES`;
const SET_ALL_SUITES = `${APP_NAME}/SET_ALL_SUITES`;
const SET_LOADING_STATUS = `${APP_NAME}/SET_LOADING_STATUS`;
const SET_FILTERED_SUITES = `${APP_NAME}/SET_FILTERED_SUITES`;

export default {
  GET_ALL_SUITES, SET_ALL_SUITES, SET_FILTERED_SUITES, SET_LOADING_STATUS,
};
