const suites = [
  {
    key: '1',
    name: 'Suite #1 Sanity',
    description: 'This suite contains all the sanity tests fro suite #1',
    labels: ['P1', 'P2'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '2',
    name: 'Suite #1 Regression',
    description: 'This suite contains all the regression tests fro suite #1',
    labels: ['P1', 'P3'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '3',
    name: 'Suite #2 Sanity',
    description: 'This suite contains all the sanity tests fro suite #2',
    labels: ['P3'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '4',
    name: 'Suite #2 Regression',
    description: 'This suite contains all the regression tests fro suite #2',
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '5',
    name: 'Suite #5 Regression',
    description: 'This suite contains all the regression tests fro suite #5',
    labels: ['P1', 'P2', 'P5'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '6',
    name: 'Suite #5 Regression',
    description: 'This suite contains all the regression tests fro suite #5',
    labels: ['P1', 'P8'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '7',
    name: 'Suite #2 Regression',
    description: 'This suite contains all the regression tests fro suite #2',
    labels: ['P1', 'P2'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '8',
    name: 'Suite #2 Regression',
    description: 'This suite contains all the regression tests fro suite #2',
    labels: ['P1', 'P2'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
  {
    key: '9',
    name: 'Suite #2 Regression',
    description: 'This suite contains all the regression tests fro suite #2',
    labels: ['P1', 'P2'],
    status: {
      passing: 20,
      failing: 2,
      unknown: 8,
      screenShotPassing: 20,
      screenShotFailing: 3,
      screenShotUnknown: 3,
    },
  },
];

export default suites;
