name: Release

on:
  push:
    branches:
      - beta

env:
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
  build: 
    name: Build to test env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get short SHA
        run: echo "GITHUB_SHA_7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - run: npm ci
      - run: npm run test:e2e -- --browser chrome
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: e2e-results
          path: |
              cypress/snapshots

